ARG NODE_VERSION=20.18.0
FROM node:${NODE_VERSION}-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm ci

COPY public/ ./public/

ENV NODE_ENV=${NODE_ENV:-production}
ENV CHOKIDAR_USEPOLLING=true
ENV WDS_SOCKET_HOST=0.0.0.0
ENV WDS_SOCKET_PORT=4000

EXPOSE 4000

CMD ["npm", "run", "dev_container"]