services:
  server:
    image: jenkins-trinity-server:back_main
    environment:
      NODE_ENV: production
      CLIENT_URL: 217.182.61.107
      PORT: 3001
      MONGODB_URI: mongodb://217.182.61.107:27017
    depends_on:
      - mongo
    networks:
      - shared_network

  mongo:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db

volumes:
  mongo:
networks:
  shared_network:
    external: true
