services:
  server-staging:
    image: ${DOCKER_IMAGE}:back_${CI_COMMIT_REF_NAME}
    environment:
      NODE_ENV: production
      CLIENT_URL: 217.182.61.107
      PORT: 9090
      MONGODB_URI: mongodb://217.182.61.107:27017
    depends_on:
      - mongodb-staging
    networks:
      - shared_network
    
  mongodb_staging:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  mongo_staging:
networks:
  shared_network:
    external: true
