services:

  client:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      environment:
        NODE_ENV: development
        PORT: 4000
        HOST: 0.0.0.0
        WATCHPACK_POLLING: true
        FAST_REFRESH: false
        REACT_APP_SERVER_URL: "http://217.182.61.107:3001"
      ports:
        - 4000:4000
      volumes:
        - ./client/src:/usr/src/app/src
        - ./client/public:/usr/src/app/public

  server:
    image: maximeparisi/jenkins-trinity-server:prod
    environment:
      NODE_ENV: production
      CLIENT_URL: 217.182.61.107
      PORT: 3001
      MONGODB_URI: mongodb://217.182.61.107:27017
    depends_on:
      - mongo
    networks:
      - shared_network

  mongo:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo:

networks:
  shared_network:
    external: true
