services:
  server-staging:
    image: ${DOCKER_IMAGE}:back_${CI_COMMIT_REF_NAME}
    environment:
      NODE_ENV: production
      CLIENT_URL: dev.gotham.titlepack.io
      MONGO_USER: $MONGO_USER
      PORT: 3001
      MONGO_HOST: mongodb-staging
      MONGODB_URI: mongodb://$MONGO_USER:$MONGO_PASSWORD@mongodb-staging:27017/$MONGO_DB_NAME?authSource=admin
      PAYPAL_CLIENT_ID: $PAYPAL_CLIENT_ID
      PAYPAL_CLIENT_SECRET: $PAYPAL_CLIENT_SECRET
      PAYPAL_RETURN_URL: https://dev.gotham.titlepack.io/#/paypalSuccess
      PAYPAL_CANCEL_URL: https://dev.gotham.titlepack.io/#/paypalError
    depends_on:
      - mongodb-staging
    networks:
      - shared_network

  mongodb-staging:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB_NAME
    volumes:
      - mongo_staging:/data/db
    networks:
      - shared_network

  mongo-express-staging:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: $ME_USER
      ME_CONFIG_BASICAUTH_PASSWORD: $ME_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USER:$MONGO_PASSWORD@mongodb-staging:27017
    networks:
      - shared_network

volumes:
  mongo_staging:
networks:
  shared_network:
    external: true
