services:
  server-staging:
    image: maximeparisi/jenkins-trinity-server:dev
    environment:
      NODE_ENV: production
      CLIENT_URL: 217.182.61.107
      PORT: 9090
      MONGODB_URI: mongodb://217.182.61.107:27018
    depends_on:
      - mongodb-staging
    networks:
      - shared_network
    
  mongodb_staging:
    image: mongo:6-jammy
    ports:
      - "27018:27018"
    volumes:
      - mongo_staging:/data/db

volumes:
  mongo_staging:
networks:
  shared_network:
    external: true
